"""Add payment_method to projects

Revision ID: 0750f7541bf6
Revises: 51c261ae4675
Create Date: 2026-03-08 14:32:34.901786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0750f7541bf6'
down_revision: Union[str, Sequence[str], None] = '51c261ae4675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('payment_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'payment_method')
    # ### end Alembic commands ###
