"""Update Presentation model for Feature 6.1.A

Revision ID: 0b8375931ad7
Revises: 47a0db682cc0
Create Date: 2026-03-07 13:26:40.355138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b8375931ad7'
down_revision: Union[str, Sequence[str], None] = '47a0db682cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presentations', sa.Column('name', sa.String(), nullable=False))
    op.add_column('presentations', sa.Column('description', sa.Text(), nullable=True))
    presentation_status = sa.Enum('DRAFT', 'PUBLISHED', 'ACCEPTED', 'REVISION_REQUESTED', name='presentationstatus')
    presentation_status.create(op.get_bind())
    op.add_column('presentations', sa.Column('status', presentation_status, nullable=False))
    op.add_column('presentations', sa.Column('branding_snapshot', sa.JSON(), nullable=True))
    op.drop_column('presentations', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presentations', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('presentations', 'branding_snapshot')
    op.drop_column('presentations', 'status')
    op.drop_column('presentations', 'description')
    presentation_status = sa.Enum('DRAFT', 'PUBLISHED', 'ACCEPTED', 'REVISION_REQUESTED', name='presentationstatus')
    presentation_status.drop(op.get_bind())
    op.drop_column('presentations', 'name')
    # ### end Alembic commands ###
