"""Add budget models and RuleType enum

Revision ID: 299f1faf8dd8
Revises: ea296ec7dc5e
Create Date: 2026-02-25 12:59:32.372585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '299f1faf8dd8'
down_revision: Union[str, Sequence[str], None] = 'ea296ec7dc5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_rules')
    sa.Enum('FLOOR', 'WALL', 'CEILING', 'UNIT', name='ruletype').create(op.get_bind())
    op.add_column('budget_items', sa.Column('rule_type', sa.Enum('FLOOR', 'WALL', 'CEILING', 'UNIT', name='ruletype'), nullable=False))
    op.add_column('budget_items', sa.Column('manual_quantity', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('budget_items_environment_id_fkey'), 'budget_items', type_='foreignkey')
    op.drop_constraint(op.f('budget_items_budget_id_fkey'), 'budget_items', type_='foreignkey')
    op.create_foreign_key(None, 'budget_items', 'environments', ['environment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'budget_items', 'budgets', ['budget_id'], ['id'], ondelete='CASCADE')
    op.drop_column('budget_items', 'name')
    op.add_column('item_options', sa.Column('is_selected', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('item_options_budget_item_id_fkey'), 'item_options', type_='foreignkey')
    op.create_foreign_key(None, 'item_options', 'budget_items', ['budget_item_id'], ['id'], ondelete='CASCADE')
    op.drop_column('item_options', 'selected')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_options', sa.Column('selected', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'item_options', type_='foreignkey')
    op.create_foreign_key(op.f('item_options_budget_item_id_fkey'), 'item_options', 'budget_items', ['budget_item_id'], ['id'])
    op.drop_column('item_options', 'is_selected')
    op.add_column('budget_items', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'budget_items', type_='foreignkey')
    op.drop_constraint(None, 'budget_items', type_='foreignkey')
    op.create_foreign_key(op.f('budget_items_budget_id_fkey'), 'budget_items', 'budgets', ['budget_id'], ['id'])
    op.create_foreign_key(op.f('budget_items_environment_id_fkey'), 'budget_items', 'environments', ['environment_id'], ['id'])
    op.drop_column('budget_items', 'manual_quantity')
    op.drop_column('budget_items', 'rule_type')
    op.create_table('application_rules',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('item_option_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rule_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('formula', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_option_id'], ['item_options.id'], name=op.f('application_rules_item_option_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('application_rules_pkey'))
    )
    sa.Enum('FLOOR', 'WALL', 'CEILING', 'UNIT', name='ruletype').drop(op.get_bind())
    # ### end Alembic commands ###
