"""add_detail_fields_to_presentation_environments

Revision ID: 3006c334dae7
Revises: 0b8375931ad7
Create Date: 2026-03-07 14:44:10.728102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3006c334dae7'
down_revision: Union[str, Sequence[str], None] = '0b8375931ad7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presentation_environments', sa.Column('title', sa.String(), nullable=True))
    op.add_column('presentation_environments', sa.Column('subtitle', sa.String(), nullable=True))
    op.add_column('presentation_environments', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('presentation_environments', sa.Column('image_urls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('presentation_environments', 'image_urls')
    op.drop_column('presentation_environments', 'description')
    op.drop_column('presentation_environments', 'subtitle')
    op.drop_column('presentation_environments', 'title')
    # ### end Alembic commands ###
