"""refactor_client_and_project_schemas

Revision ID: 368eb3cacbeb
Revises: 70acd5864243
Create Date: 2026-02-23 20:43:56.610642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '368eb3cacbeb'
down_revision: Union[str, Sequence[str], None] = '70acd5864243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('account_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('clients_project_id_fkey'), 'clients', type_='foreignkey')
    op.create_foreign_key(None, 'clients', 'accounts', ['account_id'], ['id'])
    op.drop_column('clients', 'project_id')
    op.add_column('projects', sa.Column('client_id', sa.UUID(), nullable=False))
    op.add_column('projects', sa.Column('status', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('service_type', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('service_value', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('payment_installments', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'payment_installments')
    op.drop_column('projects', 'service_value')
    op.drop_column('projects', 'service_type')
    op.drop_column('projects', 'status')
    op.drop_column('projects', 'client_id')
    op.add_column('clients', sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.create_foreign_key(op.f('clients_project_id_fkey'), 'clients', 'projects', ['project_id'], ['id'])
    op.drop_column('clients', 'account_id')
    # ### end Alembic commands ###
