"""Add created_at to ItemOption

Revision ID: 47a0db682cc0
Revises: 7e4516fc2480
Create Date: 2026-03-07 12:06:53.569725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a0db682cc0'
down_revision: Union[str, Sequence[str], None] = '7e4516fc2480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_options', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_options', 'created_at')
    # ### end Alembic commands ###
