"""Add group_id and installment_number to financial_entries

Revision ID: 4ea450ceb50c
Revises: 0750f7541bf6
Create Date: 2026-03-08 15:22:54.625788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ea450ceb50c'
down_revision: Union[str, Sequence[str], None] = '0750f7541bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_entries', sa.Column('group_id', sa.String(), nullable=True))
    op.add_column('financial_entries', sa.Column('installment_number', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_financial_entries_group_id'), 'financial_entries', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_entries_group_id'), table_name='financial_entries')
    op.drop_column('financial_entries', 'installment_number')
    op.drop_column('financial_entries', 'group_id')
    # ### end Alembic commands ###
