"""Update_FinancialEntry_schema

Revision ID: 51c261ae4675
Revises: a0b3ba95c2c9
Create Date: 2026-03-08 12:43:27.048972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c261ae4675'
down_revision: Union[str, Sequence[str], None] = 'a0b3ba95c2c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_entries', sa.Column('category', sa.String(), nullable=True))
    op.add_column('financial_entries', sa.Column('status', sa.String(), nullable=True))
    op.add_column('financial_entries', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('financial_entries', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('financial_entries', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('financial_entries', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_entries', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('financial_entries', 'updated_at')
    op.drop_column('financial_entries', 'created_at')
    op.drop_column('financial_entries', 'due_date')
    op.drop_column('financial_entries', 'status')
    op.drop_column('financial_entries', 'category')
    # ### end Alembic commands ###
