"""Add active_projects to leads

Revision ID: 5a014079c7ac
Revises: c7403ff445fa
Create Date: 2026-01-31 21:13:50.722073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a014079c7ac'
down_revision: Union[str, Sequence[str], None] = 'c7403ff445fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('active_projects', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'active_projects')
    # ### end Alembic commands ###
