"""Add loss and yield factors

Revision ID: 7e4516fc2480
Revises: 299f1faf8dd8
Create Date: 2026-03-03 20:40:58.229870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e4516fc2480'
down_revision: Union[str, Sequence[str], None] = '299f1faf8dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_items', sa.Column('loss_factor', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('yield_factor', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'yield_factor')
    op.drop_column('budget_items', 'loss_factor')
    # ### end Alembic commands ###
