"""created_by nas tabelas de dado

Revision ID: 9a5bde3fc30f
Revises: b77a9b5656c2
Create Date: 2026-09-05 13:52:19.642629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a5bde3fc30f'
down_revision: Union[str, Sequence[str], None] = 'b77a9b5656c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_logs', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'admin_logs', 'users', ['created_by'], ['id'])
    op.add_column('budget_items', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'budget_items', 'users', ['created_by'], ['id'])
    op.add_column('budgets', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'budgets', 'users', ['created_by'], ['id'])
    op.add_column('clients', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'clients', 'users', ['created_by'], ['id'])
    op.add_column('environment_dnas', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'environment_dnas', 'users', ['created_by'], ['id'])
    op.add_column('environments', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'environments', 'users', ['created_by'], ['id'])
    op.add_column('events', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'events', 'users', ['created_by'], ['id'])
    op.add_column('financial_entries', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'financial_entries', 'users', ['created_by'], ['id'])
    op.add_column('item_options', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'item_options', 'users', ['created_by'], ['id'])
    op.add_column('leads', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'leads', 'users', ['created_by'], ['id'])
    op.add_column('legal_acceptances', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'legal_acceptances', 'users', ['created_by'], ['id'])
    op.add_column('notifications', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'users', ['created_by'], ['id'])
    op.add_column('presentation_acceptances', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'presentation_acceptances', 'users', ['created_by'], ['id'])
    op.add_column('presentation_comments', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'presentation_comments', 'users', ['created_by'], ['id'])
    op.add_column('presentation_environments', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'presentation_environments', 'users', ['created_by'], ['id'])
    op.add_column('presentations', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'presentations', 'users', ['created_by'], ['id'])
    op.add_column('products', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['created_by'], ['id'])
    op.add_column('project_slots', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'project_slots', 'users', ['created_by'], ['id'])
    op.add_column('projects', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'])
    op.add_column('subscriptions', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'subscriptions', 'users', ['created_by'], ['id'])
    op.add_column('users', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_created_by_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'created_by')
    op.drop_constraint(op.f('subscriptions_created_by_fkey'), 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'created_by')
    op.drop_constraint(op.f('projects_created_by_fkey'), 'projects', type_='foreignkey')
    op.drop_column('projects', 'created_by')
    op.drop_constraint(op.f('project_slots_created_by_fkey'), 'project_slots', type_='foreignkey')
    op.drop_column('project_slots', 'created_by')
    op.drop_constraint(op.f('products_created_by_fkey'), 'products', type_='foreignkey')
    op.drop_column('products', 'created_by')
    op.drop_constraint(op.f('presentations_created_by_fkey'), 'presentations', type_='foreignkey')
    op.drop_column('presentations', 'created_by')
    op.drop_constraint(op.f('presentation_environments_created_by_fkey'), 'presentation_environments', type_='foreignkey')
    op.drop_column('presentation_environments', 'created_by')
    op.drop_constraint(op.f('presentation_comments_created_by_fkey'), 'presentation_comments', type_='foreignkey')
    op.drop_column('presentation_comments', 'created_by')
    op.drop_constraint(op.f('presentation_acceptances_created_by_fkey'), 'presentation_acceptances', type_='foreignkey')
    op.drop_column('presentation_acceptances', 'created_by')
    op.drop_constraint(op.f('notifications_created_by_fkey'), 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'created_by')
    op.drop_constraint(op.f('legal_acceptances_created_by_fkey'), 'legal_acceptances', type_='foreignkey')
    op.drop_column('legal_acceptances', 'created_by')
    op.drop_constraint(op.f('leads_created_by_fkey'), 'leads', type_='foreignkey')
    op.drop_column('leads', 'created_by')
    op.drop_constraint(op.f('item_options_created_by_fkey'), 'item_options', type_='foreignkey')
    op.drop_column('item_options', 'created_by')
    op.drop_constraint(op.f('financial_entries_created_by_fkey'), 'financial_entries', type_='foreignkey')
    op.drop_column('financial_entries', 'created_by')
    op.drop_constraint(op.f('events_created_by_fkey'), 'events', type_='foreignkey')
    op.drop_column('events', 'created_by')
    op.drop_constraint(op.f('environments_created_by_fkey'), 'environments', type_='foreignkey')
    op.drop_column('environments', 'created_by')
    op.drop_constraint(op.f('environment_dnas_created_by_fkey'), 'environment_dnas', type_='foreignkey')
    op.drop_column('environment_dnas', 'created_by')
    op.drop_constraint(op.f('clients_created_by_fkey'), 'clients', type_='foreignkey')
    op.drop_column('clients', 'created_by')
    op.drop_constraint(op.f('budgets_created_by_fkey'), 'budgets', type_='foreignkey')
    op.drop_column('budgets', 'created_by')
    op.drop_constraint(op.f('budget_items_created_by_fkey'), 'budget_items', type_='foreignkey')
    op.drop_column('budget_items', 'created_by')
    op.drop_constraint(op.f('admin_logs_created_by_fkey'), 'admin_logs', type_='foreignkey')
    op.drop_column('admin_logs', 'created_by')
    # ### end Alembic commands ###
