"""indices derivados das queries reais

Revision ID: 9b0c34de353b
Revises: 6cb3eab158e2
Create Date: 2026-09-05 15:55:52.422006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b0c34de353b'
down_revision: Union[str, Sequence[str], None] = '6cb3eab158e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_admin_logs_account_id'), 'admin_logs', ['account_id'], unique=False)
    op.create_index(op.f('ix_budget_items_account_id'), 'budget_items', ['account_id'], unique=False)
    op.create_index('ix_budget_items_budget', 'budget_items', ['budget_id'], unique=False)
    op.create_index('ix_budget_items_environment', 'budget_items', ['environment_id'], unique=False)
    op.create_index(op.f('ix_budgets_account_id'), 'budgets', ['account_id'], unique=False)
    op.create_index(op.f('ix_clients_account_id'), 'clients', ['account_id'], unique=False)
    op.create_index(op.f('ix_environment_dnas_account_id'), 'environment_dnas', ['account_id'], unique=False)
    op.create_index(op.f('ix_environments_account_id'), 'environments', ['account_id'], unique=False)
    op.create_index('ix_environments_project', 'environments', ['project_id'], unique=False)
    op.create_index('ix_events_account_start', 'events', ['account_id', 'start_time'], unique=False)
    op.create_index('ix_financial_entries_account_due', 'financial_entries', ['account_id', 'due_date'], unique=False)
    op.create_index(op.f('ix_item_options_account_id'), 'item_options', ['account_id'], unique=False)
    op.create_index(op.f('ix_leads_account_id'), 'leads', ['account_id'], unique=False)
    op.create_index(op.f('ix_legal_acceptances_account_id'), 'legal_acceptances', ['account_id'], unique=False)
    op.create_index('ix_notifications_account_created', 'notifications', ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_presentation_acceptances_account_id'), 'presentation_acceptances', ['account_id'], unique=False)
    op.create_index(op.f('ix_presentation_comments_account_id'), 'presentation_comments', ['account_id'], unique=False)
    op.create_index('ix_presentation_comments_presentation_created', 'presentation_comments', ['presentation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_presentation_environments_account_id'), 'presentation_environments', ['account_id'], unique=False)
    op.create_index(op.f('ix_presentations_account_id'), 'presentations', ['account_id'], unique=False)
    op.create_index('ix_products_account_created', 'products', ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_project_slots_account_id'), 'project_slots', ['account_id'], unique=False)
    op.create_index('ix_projects_account_created', 'projects', ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_account_id'), 'subscriptions', ['account_id'], unique=False)
    op.create_index(op.f('ix_users_account_id'), 'users', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_account_id'), table_name='users')
    op.drop_index(op.f('ix_subscriptions_account_id'), table_name='subscriptions')
    op.drop_index('ix_projects_account_created', table_name='projects')
    op.drop_index(op.f('ix_project_slots_account_id'), table_name='project_slots')
    op.drop_index('ix_products_account_created', table_name='products')
    op.drop_index(op.f('ix_presentations_account_id'), table_name='presentations')
    op.drop_index(op.f('ix_presentation_environments_account_id'), table_name='presentation_environments')
    op.drop_index('ix_presentation_comments_presentation_created', table_name='presentation_comments')
    op.drop_index(op.f('ix_presentation_comments_account_id'), table_name='presentation_comments')
    op.drop_index(op.f('ix_presentation_acceptances_account_id'), table_name='presentation_acceptances')
    op.drop_index('ix_notifications_account_created', table_name='notifications')
    op.drop_index(op.f('ix_legal_acceptances_account_id'), table_name='legal_acceptances')
    op.drop_index(op.f('ix_leads_account_id'), table_name='leads')
    op.drop_index(op.f('ix_item_options_account_id'), table_name='item_options')
    op.drop_index('ix_financial_entries_account_due', table_name='financial_entries')
    op.drop_index('ix_events_account_start', table_name='events')
    op.drop_index('ix_environments_project', table_name='environments')
    op.drop_index(op.f('ix_environments_account_id'), table_name='environments')
    op.drop_index(op.f('ix_environment_dnas_account_id'), table_name='environment_dnas')
    op.drop_index(op.f('ix_clients_account_id'), table_name='clients')
    op.drop_index(op.f('ix_budgets_account_id'), table_name='budgets')
    op.drop_index('ix_budget_items_environment', table_name='budget_items')
    op.drop_index('ix_budget_items_budget', table_name='budget_items')
    op.drop_index(op.f('ix_budget_items_account_id'), table_name='budget_items')
    op.drop_index(op.f('ix_admin_logs_account_id'), table_name='admin_logs')
    # ### end Alembic commands ###
