"""Add_Aceite_And_Notification_tables

Revision ID: ab2c2686eca3
Revises: 3006c334dae7
Create Date: 2026-03-07 18:58:27.905950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab2c2686eca3'
down_revision: Union[str, Sequence[str], None] = '3006c334dae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('presentation_acceptances', sa.Column('client_ip', sa.String(), nullable=True))
    op.add_column('presentation_acceptances', sa.Column('selected_options_snapshot', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('presentation_acceptances', 'selected_options_snapshot')
    op.drop_column('presentation_acceptances', 'client_ip')
    op.drop_table('notifications')
    # ### end Alembic commands ###
