"""Add origin to leads

Revision ID: c7403ff445fa
Revises: 9f8a3b2c1d4e
Create Date: 2026-01-31 21:05:16.031673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7403ff445fa'
down_revision: Union[str, Sequence[str], None] = '9f8a3b2c1d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('documents', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # O indice ix_documents_id ja e criado por 9f8a3b2c1d4e, a migracao
    # imediatamente anterior. Esta linha veio de um --autogenerate rodado
    # contra um banco fora de sincronia e fazia `alembic upgrade head` falhar
    # em qualquer banco vazio com DuplicateTable.
    # Ver tests/test_receita_migracoes.py.
    op.add_column('leads', sa.Column('origin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'origin')
    op.alter_column('documents', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('documents', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
