"""Add Auth v2 tables

Revision ID: d2509ab61a6f
Revises: 5a014079c7ac
Create Date: 2026-01-31 21:40:46.867155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2509ab61a6f'
down_revision: Union[str, Sequence[str], None] = '5a014079c7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('REGISTRATION', 'RECOVERY', name='verificationtokentype'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_verification_tokens_email'), 'verification_tokens', ['email'], unique=False)
    op.add_column('users', sa.Column('cpf', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['cpf'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'cpf')
    op.drop_index(op.f('ix_verification_tokens_email'), table_name='verification_tokens')
    op.drop_table('verification_tokens')
    # ### end Alembic commands ###
