"""Add Environment and DNA

Revision ID: ea296ec7dc5e
Revises: 368eb3cacbeb
Create Date: 2026-02-24 21:02:17.583361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea296ec7dc5e'
down_revision: Union[str, Sequence[str], None] = '368eb3cacbeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('environment_dnas', sa.Column('floor_area', sa.Float(), nullable=True))
    op.add_column('environment_dnas', sa.Column('wall_area', sa.Float(), nullable=True))
    op.add_column('environment_dnas', sa.Column('ceiling_area', sa.Float(), nullable=True))
    op.add_column('environment_dnas', sa.Column('is_complete', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'environment_dnas', ['environment_id'])
    op.drop_constraint(op.f('environment_dnas_environment_id_fkey'), 'environment_dnas', type_='foreignkey')
    op.create_foreign_key(None, 'environment_dnas', 'environments', ['environment_id'], ['id'], ondelete='CASCADE')
    op.drop_column('environment_dnas', 'details')
    op.add_column('environments', sa.Column('type', sa.String(), nullable=True))
    op.add_column('environments', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('environments', 'created_at')
    op.drop_column('environments', 'type')
    op.add_column('environment_dnas', sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'environment_dnas', type_='foreignkey')
    op.create_foreign_key(op.f('environment_dnas_environment_id_fkey'), 'environment_dnas', 'environments', ['environment_id'], ['id'])
    op.drop_constraint(None, 'environment_dnas', type_='unique')
    op.drop_column('environment_dnas', 'is_complete')
    op.drop_column('environment_dnas', 'ceiling_area')
    op.drop_column('environment_dnas', 'wall_area')
    op.drop_column('environment_dnas', 'floor_area')
    # ### end Alembic commands ###
